[Export]
# baked_notebookfile = true
enabled = true
output_dir = "static"

[SliderServer]
port = 8080
host = "127.0.0.1"

# You can also set Pluto's configuration here:
# [Pluto]
# [Pluto.compiler]
# threads = 2
# See documentation for `Pluto.Configuration` for the full list of options. You need specify the categories within `Pluto.Configuration.Options` (`compiler`, `evaluation`, etc).
